### ISSUE TITLE
[CLI] Add man page

### ISSUE THREAD

**Issue by Yash-Singh1** [GoogleChromeLabs/squoosh#1009]
NPM makes it simple to add man pages: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#man

**Comment by kosamari** [comment]
@surma please weigh in if this is something we want to do, if so we can make this "help wanted"

**Comment by surma** [comment]
I think it is a good idea, but likely to be blocked on #900. Ideally, the man page and the README share a common source so that we don’t have to manually keep them in sync.

**Comment by Yash-Singh1** [comment]
Maybe a GitHub workflow using `pandoc`?

**Comment by surma** [comment]
I think it might be enough to add a `publish` script.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
