### ISSUE TITLE
[LibSquoosh] Wrong main entry

### ISSUE THREAD

**Issue by SettingDust** [GoogleChromeLabs/squoosh#1034]
https://github.com/GoogleChromeLabs/squoosh/blob/dev/libsquoosh/package.json#L6
Should be `build/index.js`. 

Error on Windows.
```
Error: Cannot find module 'E:\build\index.js'. Please verify that the package.json has a valid "main" entry
```

**Comment by alexander-akait** [comment]
@surma Sorry for ping. Can you look at this? We have the same problem. Problem here https://github.com/GoogleChromeLabs/squoosh/blob/dev/libsquoosh/package.json#L6, it should be relative path, i.e. `"./build/index.js"` otherwise package is not working in `Node.js`, it is blocker to get support `Squoosh` https://github.com/webpack-contrib/image-minimizer-webpack-plugin/pull/206

**Comment by RReverser** [comment]
> it should be relative path, i.e. "./build/index.js"

Do you want to make a PR? Should be a quick change.

**Comment by atjn** [comment]
I believe `./build/index.js` is the correct way to do it, but only because that's how I have seen other packages do it. I don't think anyone has ever documented what the best/correct solution is.

I wouldn't mind adding a PR for this, but since no one has provided a valid test case, I can't test if it actually solves the problem. I just did a quick test implementation on Node 14.17 on Windows, and everything worked as it should without any modifications.

**Comment by alexander-akait** [comment]
@RReverser done https://github.com/GoogleChromeLabs/squoosh/pull/1041
