### ISSUE TITLE
Enable navigationPreload in the service worker

### ISSUE THREAD

**Issue by feross** [GoogleChromeLabs/squoosh#1047]
Hey folks! I've been looking at the Squoosh service worker code as an inspiration as I've been building [Wormhole](https://wormhole.app). Thanks for open sourcing this – it's quite helpful!

One question – is there a reason why you haven't enabled the [`navigationPreload`](https://developers.google.com/web/updates/2017/02/navigation-preload) option? I've found that it causes extra network requests even for cached content and was wondering if perhaps that's why you've not enabled it here.

Apologies if this isn't the correct forum for this question. Thanks again!

**Comment by jakearchibald** [comment]
Navigation preload is only useful if you need content from the network as part of a navigation.

For instance, an app like Twitter may do a navigation preload of the main timeline JSON, so that request can start even while the service worker is still spinning up.

With Squoosh we don't need any network data as part of our render - it's entirely cached, so there's nothing to preload as part of navigation preload.

(Closing this, but I'm happy to continue discussing)

**Comment by feross** [comment]
@jakearchibald Thanks for the response!

> an app like Twitter may do a navigation preload of the main timeline JSON

Can you actually select which requests get preloaded with navigation preload? It seemed to me like the API was all-or-nothing. Of course, you can avoid using the `preloadResponse ` but won't the HTTP requests be made anyway?

**Comment by jakearchibald** [comment]
> Can you actually select which requests get preloaded with navigation preload?

Nah, but you can set a header to go along with the request. That means the server can return something different for nav-preload requests. I guess it could return an empty response in places where you know you won't use the response.
