### ISSUE TITLE
Add supported node versions to @squoosh/cli and @squoosh/lib readmes

### ISSUE THREAD

**Issue by ergunsh** [GoogleChromeLabs/squoosh#1059]
**Describe the bug**
Currently, when I try to run the cli in different node versions, different kind of errors are occurring related to imports.

As far as I understand, support for named exports came to Node at v14.13.0 ([Release notes](https://nodejs.org/en/blog/release/v14.13.0/)) and we need it. For example, when I run in v14.0.0, I get this error:
```
import { ImagePool, preprocessors, encoders } from '@squoosh/lib';
                                   ^^^^^^^^
SyntaxError: The requested module '@squoosh/lib' does not provide an export named 'encoders'
```

I guess there are two possible things we can do:
* Document the Node versions we support (as v14.13.0 for CLI and I don't know for libSquoosh 😅 )
* Update build config to support more node versions and document the ones we support in readme

**To Reproduce**
1. Install Node v14.0.0 (via nvm: `nvm install v14.0.0`)
2. Use Node v14.0.0 (via nvm: `nvm use v14.0.0`)
3. Install @squoosh-cli globally (via `npm install -g @squoosh/cli`)
4. Run the CLI (via `squoosh-cli`)
5. Observe that there is an error related to imports

**Expected behavior**
The import error shouldn't happen (or people should know and not use CLI prior to Node v14.13.0)

**Version:**
 - Node version: 14.0.0
 - npm version: 6.14.4

**Comment by surma** [comment]
Yeah, we support all Node version since LTS (so 12, 14, 16), but we do expect the most recent of those respective major releases. Happy to take a PR to update the README accordingly.

(also cheekily cc’ing @atjn if he has opinions on this)

**Comment by atjn** [comment]
My thought process when releasing this was simply that for an _experimental_ program, it was okay to remove support for Node versions that have active security vulnerabilities, and that can very easily be updated to a new version, especially because it gave us some nice perks to be able to use the new import syntax.

I completely agree it should be documented somewhere, in the docs and/or in `package.json`. If you define it in `package.json`, npm will warn anyone that tries to install it with an unsupported Node version. I'll happily provide a PR for that :)

**Comment by surma** [comment]
Yeah I was trying to remember if `engines` in `package.json` would generate a warning. This SGTM! PRs appreciated :)

**Comment by atjn** [comment]
Cool, I'll make a PR for the `package.json` thing. Ideally, the docs should be updated based on what is set in `package.json`. I'm not sure if there are plans for a system that facilitates that.
