### ISSUE TITLE
[CLI] Make it run on the web

### ISSUE THREAD

**Issue by kosamari** [GoogleChromeLabs/squoosh#1084]
Run command from Web interface 
TODO: needs more detail on implementation

**Comment by styfle** [comment]
Are you looking to make `@squoosh/cli` work on the web, or just `@squoosh/lib`?

**Comment by surma** [comment]
The CLI would remain a thing wapper for the command line around `@squoosh/lib`  :)

**Comment by styfle** [comment]
Great! What are the steps to get it working on the web?

**Comment by surma** [comment]
Sorry for taking so long to reply. 

cc @atjn as he might have opinions on this.
Also cc @ergunsh, who is working on TypeScriptifying libSquoosh, in case he has thoughts/concerns.

---

To get libSquoosh running on the web I was thinking something along these lines:

- _Remove_ the capabilities to pass file paths to `ImagePool`. Loading from the file system should be the responsibility of the CLI, not the lib.
- Remove the `web-streams-polyfill` from the library and generate a node-specific output instead.
- Expose a hook/async callback to load Wasm modules. Since Node, Deno and web will all rely on different APIs to load a .wasm file.
- Use `new URL(..., import.meta.url)` to reference .wasm files so that bundlers can handle the .wasm assets correctly.

Did I miss anything? What do y’all think?

**Comment by atjn** [comment]
That seems good to me. One quick note:

> Remove the capabilities to pass file paths to `ImagePool`. Loading from the file system should be the responsibility of the CLI, not the lib.

Being able to pass a file path directly to `ImagePool` is a pretty big nice-to-have IMO. If we have to build separate versions anyway, I would consider using the `fs.readFile` function to load images in Node, which has a lot of Node-specific nice-to-haves, including loading files directly from a path :)

I also have two questions that I think could be good to know for us non-core contributors:

1. Creating separate builds for so many different environments requires a lot of resources, not just initially but also to maintain the different builds in the future. Do you expect to be able to dedicate those resources? If not, you could just turn `libSquoosh` into a web-only package and create wrappers for Node and Deno that use [`puppeteer`](https://github.com/puppeteer/puppeteer) to run it. It might not be as elegant, but if the alternative is an abandoned package, or one that constantly has breaking bugs, then I'd prefer the inelegant solution :)

2. Is the plan to eventually use `libSquoosh` on the website? Should we be thinking on ways to make that happen, or would you like to keep them separate, at least for now?

Maybe stuff like this could be added to [`CONTRIBUTING.md`](https://github.com/GoogleChromeLabs/squoosh/blob/ad5002c79cccab7291b7bbb5d9f6270087ca6d4e/CONTRIBUTING.md) so everyone is on the same page about what we're doing :)

**Comment by styfle** [comment]
> turn libSquoosh into a web-only package and create wrappers for Node and Deno that use puppeteer to run it

I think puppeteer would be too bloated. Instead, we should strive to make libSquoosh to work on both the web and node.js using isomorphic/universal JS.

**Comment by ergunsh** [comment]
Sorry for taking a late look 😅

I think there is one more thing we need to consider while making libSquoosh available on web: usage of `worker_threads` which is only available in NodeJS. So, we'll need to replace it with web workers on web.

**Comment by styfle** [comment]
Without looking at the code, it might make more sense to reduce the scope of libsquoosh be the bare minimum for optimizing images. Meaning no workers, just plain JS thats compatible everywhere (as opposed to polyfilling each possible runtime).

Then it can serve as the foundation for which node, deno, web, etc wrap around and provide features like workers, etc.

Although I admit I might be misunderstanding the boundaries between squooshcli, squooshlib, and perhaps other packages in this monorepo.

**Comment by atjn** [comment]
I believe we have talked about maybe releasing every encoder/decoder as its own package. Those packages could probably work across all runtimes.

Other than that, I don't think you can produce any meaningful piece of code that can run across all runtimes. Even just loading the encoders/decoders will require runtime-specific APIs.

**Comment by surma** [comment]
> Being able to pass a file path directly to ImagePool is a pretty big nice-to-have IMO.

I can see that. In retrospect, my envisioned API actually covers this quite easily. So let’s keep that for now :D

> Creating separate builds for so many different environments requires a lot of resources

I don’t _think_ it does. See below! But please continue voicing your concerns, if there are any!

> Is the plan to eventually use libSquoosh on the website? 

Very very long term, _maybe_. For now, no.

> I think puppeteer would be too bloated.

+1

---

Let’s iterate with a concrete API proposal:

I like the idea of providing very thin convenience wrappers from Deno, Node and Web out of the box. But I also believe there is value in a runtime/platform agnostic core, and I think we can achieve that. 

The only primitive that is inconsistent between our supported runtimes is Web Workers, where Node implements something slightly incompatible. We should be able to iron out the kinks there just by using @developit’s [web-worker package](https://npm.im/web-worker). 

Here’s how I’d envision that API to work:

```ts
// I’m gonna continue using `ImagePool` as 
// the main API primitive exposed from libSquoosh. 
import {ImagePool} from "@squoosh/lib";

// On the web:
const pool = new ImagePool({
	// Called for .wasm files and for image paths
    // if `ingestImage()` is called with a string.
	loadFile: (path: URL): Promise<ArrayBuffer> => fetch(path).then(r => r.arrayBuffer()),
});

// Deno:
const pool = new ImagePool({
	loadFile: (path: URL): Promise<ArrayBuffer> => Deno.readFile(path)),
});

// Node:
const pool = new ImagePool({
	loadFile: (path: URL): Promise<ArrayBuffer> => require("fs/promises").readFile(path.pathname)),
});
```

What do you all think? Please critique away!

**Comment by styfle** [comment]
> Is the plan to eventually use libSquoosh on the website?
>> Very very long term, maybe. For now, no.

I'm curious, if the website isn't using libSquoosh, then what is it using today? 

> I believe we have talked about maybe releasing every encoder/decoder as its own package.

Like this? https://github.com/cyrilwanner/wasm-codecs

**Comment by atjn** [comment]
> > Is the plan to eventually use libSquoosh on the website?
> > > Very very long term, maybe. For now, no.
> 
> I'm curious, if the website isn't using libSquoosh, then what is it using today?

The website is using the same wasm codecs as libSquoosh, but it bypasses libSquoosh and uses the codecs directly. If it was to instead ask libSquoosh to compress the images, then we wouldn't have to write separate logic for both web and lib for instantiating and controlling a compression process (which would, at least in theory, be easier to understand and maintain).

> > I believe we have talked about maybe releasing every encoder/decoder as its own package.
> 
> Like this? https://github.com/cyrilwanner/wasm-codecs

Exactly like that, although it seems like @cyrilwanner is making some custom changes to these codecs. Maybe we could merge these changes into Squoosh and release them as official codecs directly from this repository instead?

**Comment by surma** [comment]
The main reason that the PWA does not use libSquoosh is that the PWA came first :D

Another reason is that the PWA has different constraints: We are only ever processing exactly one image, one worker per side of the split view, and each worker only ever processes one compression job. If a change comes in, the worker gets hard-interrupted and a new one gets created. We also make extensive use of lazy loading and code splitting in the PWA. Download size and memory footprint matter much more in the context of the PWA than they do in a build step.

On the one hand, I’d like to make a change to libSquoosh and have both the CLI and the PWA benefit from it, but it will be a considerable amount of work to adapt libSquoosh to remain useful for the CLI but also to stay within the constraints of the PWA. 

_At least for now_ — because the PWA has been around longer and is more  mature and stabile than the CLI, not to mention libSquoosh — I am happy to duplicate some work between these two. 

----

@styfle Do you fancy taking a stab at implementing the API sketch outlined above?

**Comment by styfle** [comment]
> Download size and memory footprint matter much more in the context of the PWA than they do in a build step.

The purpose of this issue, "Make it run on the web", would have many of the same constraints and https://squoosh.app

I think its imperative to get https://squoosh.app using the same code published here.

Otherwise, other consumers whether thats web/node/deno will not match squoosh.app because its not truly [dogfooding](https://en.wikipedia.org/wiki/Eating_your_own_dog_food).

> release them as official codecs directly from this repository instead?

Sounds good to me 👍

**Comment by surma** [comment]
In the long term, I agree. But step one for me would be to just make it run on the web. Then make it “right”. Then integrate it with the PWA. I don’t want to take all these steps at once to avoid extensive mental gymnastics in the code reviews.

**Comment by styfle** [comment]
Ok I can implement the [proposed API](https://github.com/GoogleChromeLabs/squoosh/issues/1084#issuecomment-885605209) 👍 

Do I need to wait for the "[TypeScriptifying libSquoosh](https://github.com/GoogleChromeLabs/squoosh/issues/1084#issuecomment-881328237)" PR to land first?

**Comment by surma** [comment]
Amazing. Thank you so much, @styfle.

I am not sure if @ergunsh is _currently_ actively working on the Typescriptification, but I’d say get going! We can always resolve the conflicts. Don’t want to block either of you :)

**Comment by styfle** [comment]
I converted the remaining JS to TS in PR #1110

**Comment by j-maas** [comment]
I just ran into a tricky bug with the pool when used with another library that uses workers (an `ImagePool` worker picked up a message from the `parentPort` that was supposed to go to another worker). So forked the lib and stripped out the `ImagePool` which resolved the issues (it's a pretty brute force solution, admittedly).

But I thought that it might be worth providing a pool-less API and not force every user to use the `ImagePool`. What I could imagine is that `Image` would work on its own without the pool (`const image = new Image(path); image.encode(options);`). If you wanted the multithreading, you would use the pool. Then you'd either pass a regular image to the pool (`imagePool.encode(image, options)`) or you'd have a separate `ImagePoolHandle` which works the same as the current `Image` (i.e., `const handle = imagePool.ingest(path); handle.encode(options);`).

This is just a suggestion. Feel free to do with it what you see fit. ;)

**Comment by j-maas** [comment]
If you're curious about my changes, they are available at https://github.com/Y0hy0h/squoosh/commit/3e1759613e8f7e1a07eb63beb323110fd1e832e0.

**Comment by Y0hy0h** [comment]
If you're curious about my changes, they are available at https://github.com/Y0hy0h/squoosh/commit/3e1759613e8f7e1a07eb63beb323110fd1e832e0.

**Comment by styfle** [comment]
@surma I created #1123, but we can't use a async `loadFile()` unless we want to make `ingestImage()` async as well.

**Comment by styfle** [comment]
For those following along at home: 

- #1123 has landed
- Jason is going to make a [follow up PR](https://github.com/GoogleChromeLabs/squoosh/pull/1123#issuecomment-914694991) to finish up the remaining work: using `web-worker` instead of `worker_threads`

After that, we should be ready to run `@squoosh/lib` on the web 🕸️

**Comment by adamsilverstein** [comment]
@styfle/@surma looks like this is almost ready for testing? 

I'm trying to follow along on https://github.com/GoogleChromeLabs/squoosh/tree/dev/libsquoosh to add squoosh to my modern images [plugin](https://github.com/adamsilverstein/modern-images-wp/issues/18). Can I test this by building squoosh or do you plan an `npm` release soon with this included?

**Comment by atjn** [comment]
@adamsilverstein everything in [styfle's comment](https://github.com/GoogleChromeLabs/squoosh/issues/1084#issuecomment-915592530) is still true - there is still some work to do before a working npm release will be ready.
If you build from source, you might be able to hack your way to a working plugin :)

**Comment by developit** [comment]
There is still work to do to have WASM loading be cross-platform.

**Comment by mivanyna** [comment]
Hi. Any updates on this one?

**Comment by msfragala** [comment]
I'd love to use this for a side project. Seems like there hasn't been much activity lately — how can I help get this across the finish line?

**Comment by donmccurdy** [comment]
^Same — would love to help with anything (code, unit test, manual testing, etc.) if we can move this forward. It's been a [pretty popular request](https://twitter.com/AdaRoseCannon/status/1513485574438592518) to bring squoosh/lib into https://gltf.report/ for optimizing glTF 3D files. I've done the integration for [processing glTF files with squoosh](https://gltf-transform.donmccurdy.com/functions.html#webp), it just doesn't run on the web app yet.

**Comment by radulle** [comment]
I would like to help too. How could we organise to make this happen?

Sqoosh does seem to have been abandoned? https://github.com/GoogleChromeLabs/squoosh/graphs/commit-activity

I found this effort of bringing squoosh to web https://github.com/myeveryheart/squoosh-browser.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.

**Comment by atjn** [comment]
I have shifted focus to work on [wasm-vips](https://github.com/kleisauke/wasm-vips), and would suggest that everyone else uses and/or contributes to that instead. Of course it would also be cool to have an alternative based on squoosh binaries if someone wants to build and maintain that.
