### ISSUE TITLE
libsquoosh: Don't take the whole buffer from a view, respect byteOffset and byteLength

### ISSUE THREAD

**Issue by mjpieters** [GoogleChromeLabs/squoosh#1095]
**Describe the bug**
libsquoosh accepts [buffer views](https://nodejs.org/api/buffer.html), and unwraps these:

https://github.com/GoogleChromeLabs/squoosh/blob/ad5002c79cccab7291b7bbb5d9f6270087ca6d4e/libsquoosh/src/index.js#L13-L15

Tools like webpack work with these kinds of buffers, where the typed array is a view on a _larger_ buffer. However, the way libsquoosh converts views is problematic: it takes the whole underlying buffer.

**To Reproduce**

Create a larger buffer, load in a small PNG somewhere past the starting point, and feed that to the image pool; the image file I used (https://upload.wikimedia.org/wikipedia/commons/7/70/Example.png) is 2335 bytes small but embedded in an 8kb buffer:

```js
const ImagePool = require('@squoosh/lib').ImagePool
const https = require('https')
const url = 'https://upload.wikimedia.org/wikipedia/commons/7/70/Example.png'

function httpsIntoBuffer(url, buffer, offset) {
  // put data from url into buffer starting at offset, return slice over
  // downloaded data
  return new Promise((resolve, reject) => {
    const req = https.get(url, (resp) => {
      pos = offset
      resp
        .on('data', (chunk) => { buffer.fill(chunk, pos); pos += chunk.length })
        .on('end', () => resolve(buffer.slice(offset, pos)))
        .on('error', (err) => reject(err))
      req.on('error', (err) => reject(err)).end()
    })
  })
}

async function mcve() {
  const pool = new ImagePool()
  try {
    // read PNG into section of larger buffer
    const buffer = Buffer.alloc(8192)
    const view = await httpsIntoBuffer(url, buffer, 1024)
    const image = pool.ingestImage(view)
    console.log(await image.decoded)
  } catch (err) {
    console.error(err)
  }
  pool.close()
}

mcve()
```

output:

> Binary blob has an unsupported format

**Expected behavior**
I would expect the above to work, where libsquoosh uses:

```js
 if (ArrayBuffer.isView(file)) { 
   buffer = Buffer.from(file.buffer.slice(file.byteOffset, file.byteOffset + file.byteSize)); 
```

Passing in the explicit slice works when replacing the `ingestImage()` call with:

```js
const image = pool.ingestImage(view.buffer.slice(view.byteOffset, view.byteOffset + view.byteLength))
```

which produces:

```
{
  bitmap: {
    data: Uint8ClampedArray(122464) [
      244, 209, 13, 255, 244, 209, 13, 255, 244, 209, 13, 255,
      244, 209, 13, 255, 244, 209, 13, 255, 244, 209, 13, 255,
      244, 209, 13, 255, 244, 209, 13, 255, 244, 209, 13, 255,
      244, 209, 13, 255, 244, 209, 13, 255, 244, 209, 13, 255,
      244, 209, 13, 255, 244, 209, 13, 255, 244, 209, 13, 255,
      244, 209, 13, 255, 244, 209, 13, 255, 244, 209, 13, 255,
      244, 209, 13, 255, 244, 209, 13, 255, 244, 209, 13, 255,
      244, 209, 13, 255, 244, 209, 13, 255, 244, 209, 13, 255,
      244, 209, 13, 255,
      ... 122364 more items
    ],
    width: 172,
    height: 178
  },
  size: 2335
}
```

**Version:**
 - OS w/ version: macOS 10.15
 - Node version: 15.14.0
 - npm version: 7.14.0

**Comment by aprilmintacpineda** [comment]
I just experienced this now, seems hasn't been fixed yet.

EDIT:

Seems to only happen after I have uploaded the picture to S3 and then grabbed (`s3.getObject`) it in order to process it.
This is the image that I'm talking about. I tried to download it and I was able to replicate the issue on my local machine.

![IMG](https://user-images.githubusercontent.com/21032419/155840446-55699932-b382-47a5-a208-710781709dcd.jpeg)

```ts
import { promises as fs } from 'fs';
// eslint-disable-next-line
// @ts-ignore
import { ImagePool } from '@squoosh/lib';

(async () => {
  const file = await fs.readFile('./IMG.jpeg');

  const imagePool = new ImagePool();
  const image = imagePool.ingestImage(file);
  await image.decoded;

  await image.encode({
    mozjpeg: {
      quality: 70
    }
  });

  await imagePool.close();
  const imageContent = await image.encodedWith.mozjpeg;

  await fs.writeFile('./IMG_optimized.jpg', imageContent.binary);
})();
```

And it would seem that even github can't process  the image, lol.

Here's the compressed, together with the original image (before upload to s3)
[Archive.zip](https://github.com/GoogleChromeLabs/squoosh/files/8146423/Archive.zip)

I also noticed that VSCode is having a hard time reading it

![image](https://user-images.githubusercontent.com/21032419/155840516-c687c6f4-c16a-447b-808e-f1b39486baed.png)

The browser also can't load it.

**Comment by jakearchibald** [comment]
> the way libsquoosh converts views is problematic: it takes the whole underlying buffer.

Yeah, this seems like a bug, thanks for reporting.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
