### ISSUE TITLE
Add function to cleanup wasm memory

### ISSUE THREAD

**Issue by styfle** [GoogleChromeLabs/squoosh#1097]
We found that Next.js had a memory leak when pooling squoosh workers.

This was patched in https://github.com/vercel/next.js/pull/23565 with this:

```js
export function cleanup() {
  wasm = null
  cachegetUint8ClampedMemory0 = null
  cachegetUint8Memory0 = null
  cachegetInt32Memory0 = null
}
```

Then cleanup would be called in `codecs.ts`.

Any interest in adding this patch to `@squoosh/lib`?

**Comment by surma** [comment]
Interesting! Definitely interested in patching the leaks. While this is not an ideal solution, it’s better than leaving the leaks. So happy to accept an PR for this, although we should open a separate issue to investigate where we are leaking at some point.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
