### ISSUE TITLE
Integrate with graphql api 

### ISSUE THREAD

**Issue by shohinrahmonov** [GoogleChromeLabs/squoosh#1108]
**Describe the bug**
tried to integrate with my backend graphql api but i got the following error
<img width="687" alt="Screenshot 2021-07-25 at 5 31 15 PM" src="https://user-images.githubusercontent.com/22424923/126894535-528b2720-2ac7-4693-93bd-b398b974802e.png">

**Comment by surma** [comment]
Can you put a reproduction sample in a gist?

**Comment by shohinrahmonov** [comment]
@surma here please https://gist.github.com/shohinrahmonov/5f25629ee4ac10dde5f692078fa8f564

**Comment by surma** [comment]
That’s not a reproduction sample. That’s a code snippet. I need something I can run to reproduce the error locally. What Node version are you running?

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.

**Comment by songkeys** [comment]
But why the source code was removed? https://github.com/GoogleChromeLabs/squoosh/tree/dev/libsquoosh

**Comment by jakearchibald** [comment]
See the previous message
