### ISSUE TITLE
Cannot find module: avif_node_enc_mt.worker-be931951.js [Windows]

### ISSUE THREAD

**Issue by Draghmar** [GoogleChromeLabs/squoosh#1119]
**Describe the bug**
I wanted to try running cli on Win10 but I got error:
```
PS C:\Users\konta> squoosh-cli --avif "{speed:5,cqLevel:18,subsample:2}" Q:\test.jpg
0/1 ⠦ ▐▨▨▨▨▨╌╌╌╌╌▌ Encoding (8 threads)
 Q:\test.jpg: 258.25KB
node:internal/event_target:646
  process.nextTick(() => { throw err; });
                           ^
Error: Cannot find module 'C:\C:\Users\konta\AppData\Roaming\npm\node_modules\@squoosh\cli\node_modules\@squoosh\lib\build\avif_node_enc_mt.worker-be931951.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:187:24)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:460:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:298:10)
    at Worker.[kOnMessage] (node:internal/worker:309:37)
    at MessagePort.<anonymous> (node:internal/worker:210:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:460:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
I did try to run `npm i -g @squoosh/cli@latest` and `npx @squoosh/cli`. In both cases the result was the same.

**Version:**
 - OS w/ version: Win10 Pro
 - Node version: v16.6.2
 - npm version: 7.20.5

**Comment by surma** [comment]
@jcao219 Do you think you can take a look at this?

**Comment by jcao219** [comment]
Interesting bug! I'm able to reproduce this on Windows 10 also. The same line works on WSL. I'll look deeper into it tomorrow.

**Comment by jcao219** [comment]
The problem may come from this line:

https://github.com/GoogleChromeLabs/squoosh/blob/816d1f92fdd60c4492cf55d75d729db40f64bb0e/libsquoosh/src/emscripten-utils.ts#L22

`workerJS` is something like `file:///C:/some/windows/stuff/worker.js`

This is valid, but `new URL(workerJS).pathname` becomes `/C:/some/windows/stuff/worker.js` which gets wrongly interpreted as `C:\C:\some\...` (notice the double drive mount) somewhere down the line.

Instead of using `new URL(...).pathname`, `pathify` handles it correctly. The other option of trimming the leading slash to make `/C:/` into `C:/` also works.

@surma Any reason why this line doesn't use `pathify` like the line above it?

**Comment by surma** [comment]
@jcao219 Probably an oversight? Me trying to be clever? Either way, we should fix it. Do you fancy whipping up a PR (allowing you to make sure it’s actually fixing the problem at hand)? Thanks for looking into this!

**Comment by jcao219** [comment]
Sorry for the delay! My PR should fix it: #1138

**Comment by Th3S4mur41** [comment]
@surma is there already a plan to release a new cli version with this patch?

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.

**Comment by aggregate1166877** [comment]
@Draghmar @Th3S4mur41

I'm currently maintaining a fork with the CLI stuff [here](https://www.npmjs.com/package/@frostoven/squoosh-cli) that fixes this issue if you're still hoping for a fix on the CLI side.
