### ISSUE TITLE
[CLI] Problem identifying options from the webapp with the CLI version

### ISSUE THREAD

**Issue by juan88** [GoogleChromeLabs/squoosh#1150]
Is it possible to include and document the options that are available in the webapp in the same terms as in the CLI? I'm not able to find, for example, the lossless flag of the AVIF encoder to use in the CLI version.

Thanks!

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
