### ISSUE TITLE
Import CLI command

### ISSUE THREAD

**Issue by strarsis** [GoogleChromeLabs/squoosh#1155]
**Is your feature request related to a problem? Please describe.**
After having determined the optimal settings for a particular image, resolution and format, I save the CLI command and store in my build tasks. This also preserves all the settings, to make the result reproducible.
However, I can't find a way to import this CLI command back into Squoosh and get the settings back.

**Describe the solution you'd like**
A mechanism to import existing CLI commands (as exported from Squoosh) so the settings can be restored.

**Does other service/app have this feature?**
No, I want to use Squoosh as it offers great features.

**Additional context**
Related issue (make CLI commands run in Squoosh): https://github.com/GoogleChromeLabs/squoosh/issues/1084

**Comment by AforDesign** [comment]
Importing CLI-commands and/or saving presets in the app would be a huge improvement.

Especially when working with AVIF which has many parameters to set.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
