### ISSUE TITLE
CLI requires explicitly passing in "true" to switch options

### ISSUE THREAD

**Issue by SUPERCILEX** [GoogleChromeLabs/squoosh#1159]
This broke somewhere between 0.6.3 and 0.7.2. If you use the `--mozjpeg` option for example, squoosh will crash:

```
file:///home/asaveau/IdeaProjects/personal-website/.build/node_modules/@squoosh/cli/src/index.js:173
        encParam.toLowerCase() === 'auto' ? 'auto' : JSON5.parse(encParam);
                 ^

TypeError: encParam.toLowerCase is not a function
    at Command.processFiles (file:///home/asaveau/IdeaProjects/personal-website/.build/node_modules/@squoosh/cli/src/index.js:173:18)
```

So `$ squoosh-cli ... --mozjpeg` fails, but `$ squoosh-cli ... --mozjpeg true` works. It looks to me like the default case is being parsed as an actual boolean whereas the explicit case returns a string.

**Comment by craftedsystems** [comment]
Same with `--webp` option.

[cli/src/index.js#L176](https://github.com/GoogleChromeLabs/squoosh/blob/66ec7636675707e34e7991435b3a2df970d9ae62/cli/src/index.js#L176)
☝️ `encParam` is `true` (boolean) and not a string. 💥🙂

**Comment by simonsarris** [comment]
Same. To be clear for onlookers who are searching based on the `TypeError: encParam.toLowerCase is not a function` error,

`squoosh-cli --oxipng --quant 50 blah.png`

will fail, and:

`squoosh-cli --oxipng true --quant 50 blah.png`

will succeed.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
