### ISSUE TITLE
Wish: Accept input from STDIN, provide output to STDOUT

### ISSUE THREAD

**Issue by markstos** [GoogleChromeLabs/squoosh#1175]
**Is your feature request related to a problem? Please describe.**

I use `swappy` as a screenshot editing tool. Swappy accepts the image data on STDIN, so it's convenient to use it with `grimshot`, which saves screenshots to STDOUT. Together they are used like this:

      grimshot save area - | swappy -f -

**Describe the solution you'd like**

I'd like a variation of this to work: 

    grimshot save area - | squoosh | swappy -f -

`squoosh` seems like a natural fit to work as a Unix filter since it transforms images.

**Does other service/app have this feature?**

Yes, as seen above, there are other Linux tools that pass image data through STDIN and STDOUT. Another example is `wl-copy`:

    grimshot save area - | squoosh | wl-copy --type image/png

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
