### ISSUE TITLE
Can't compress content of directory when there's unsupported files inside

### ISSUE THREAD

**Issue by hybridherbst** [GoogleChromeLabs/squoosh#1179]
**Describe the bug**
Being able to copy the squoosh CLI command from the website is very powerful (in theory) for batch processing.
However, it seems there's a couple blockers, such as squoosh stopping to do anything when it encounters unsupported files, or filter masks not working.

**To Reproduce**
1. Go to https://squoosh.app/editor
2. Copy the command
3. Open a terminal in a folder that contains both images and other stuff (e.g. a .meta file for each image, a Readme.txt file, ...)
4. Paste the command, append "./" to run in the entire folder
5. Press Enter.
6. Note that there's a bunch of "UnhandledPromiseRejectionWarning: some_file.jpg.meta has an unsupported format"

I also tried appending `*`, `*.jpg"`, `./*.jpg` etc. but these all just return 
```UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat 'E:\git\bugs\squoosh\Stuff\*.jpg'```

**Expected behavior**
Files in folder that can be squooshed are squoosed, there's warnings for other files but no unhandled exceptions

**Version:**
 - OS w/ version: [e.g. Windows 10]
 - Node version: [14.18.0]
 - npm version: [6.14.15]

**Comment by hybridherbst** [comment]
Might be a duplicate of #973

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
