### ISSUE TITLE
CLI running out of memory

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/squoosh#1185]
[this image](https://storage.googleapis.com/atoms-sandbox.google.com.a.appspot.com/frame.png) is running out memory with the cli command. i def have enough memory, and the image compresses/converts fine in the web app.

```bash
npx @squoosh/cli --avif '{"cqLevel":33,"cqAlphaLevel":-1,"denoiseLevel":0,"tileColsLog2":0,"tileRowsLog2":0,"speed":6,"subsample":1,"chromaDeltaQ":false,"sharpness":0,"tune":0}' ./frame.png
```

**Comment by argyleink** [comment]
<img width="732" alt="Screen Shot 2021-11-05 at 11 15 37 AM" src="https://user-images.githubusercontent.com/1134620/140559953-cc473b8d-9057-4dad-b71e-31d6c88b83e8.png">

**Comment by surma** [comment]
@argyleink Oh can you let me know your Node version and whether you are on an M1 or Intel?

**Comment by surma** [comment]
Damn, it works just fine on my machine with Node 16 and Node 17 😅

**Comment by argyleink** [comment]
> @argyleink Oh can you let me know your Node version and whether you are on an M1 or Intel?

Node 16, Intel

**Comment by coelmay** [comment]
Not working properly for me on an Intel iMac running node `v16.10.0`.
Runs fine on Chromebook running `v14.17.6`

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
