### ISSUE TITLE
Husky breaks npm install

### ISSUE THREAD

**Issue by heddn** [GoogleChromeLabs/squoosh#1190]
**To Reproduce**
As mentioned in https://github.com/GoogleChromeLabs/squoosh/pull/1170.

```
curl -OL https://github.com/GoogleChromeLabs/squoosh/archive/dev.zip
unzip dev.zip
cd squoosh-dev
npm install
```

**Expected behavior**
I would expect the code could be compiled w/ or w/o .git folder existing.

**Version:**
 - OS w/ version: Linux
 - Browser w/ version n/a
 - Node version: v14.18.1
 - npm version: 6.14.15

**Additional context, screenshots, screencasts**
Error:
```
$ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> squoosh@2.0.0 prepare /var/www/html/libraries/squoosh-dev
> husky install

.git can't be found (see https://git.io/Jc3F9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! squoosh@2.0.0 prepare: `husky install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the squoosh@2.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by heddn** [comment]
From looking at https://github.com/typicode/husky/issues/851, we have some options, including updating to a newer version of husky.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
