### ISSUE TITLE
@squoosh/cli does not support GIF

### ISSUE THREAD

**Issue by PashaGeronimo** [GoogleChromeLabs/squoosh#1210]
When I try to convert from GIF I get this error
_Binary blob has an unsupported format_
Other formats work fine (jpg, png)

Node v16.13.0

```
origImage = await s3.getObject({ Bucket: dstBucket, Key: inputImgPath }).promise();
image = imagePool.ingestImage( origImage.Body);
await image.decoded;
await image.encode({ });
const outBuffer = (await image.encodedWith.avif).binary;
```

**Comment by surma** [comment]
Yeah you are absolutely fine. The CLI doesn’t support GIF. In the web app we can rely on the browser to decode GIFs. In Node we’d have to ship a decoder of our own and I completely forgot about this format. If anyone wants to add a wasm GIF decoder, that’d be welcome.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
