### ISSUE TITLE
publish 0.4.1/0.5.0?

### ISSUE THREAD

**Issue by patrickkettner** [GoogleChromeLabs/squoosh#1223]
Hiya!
<s>Any chance version [0.4.1](https://github.com/GoogleChromeLabs/squoosh/tree/2238d1abaf89d662a87cce9f9724a77c761a3d97) and/or [0.5.0](https://github.com/GoogleChromeLabs/squoosh/commit/c24505230d85404104d3d843cacb372cbed2a6da) or libSquoosh is going to be published on npm?</s>

Update: found the deprecation note for [0.4.1](https://www.npmjs.com/package/@squoosh/lib/v/0.4.1), any chance the bugs are listed anywhere?

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
