### ISSUE TITLE
Processing error: ReferenceError: WebAssembly is not defined

### ISSUE THREAD

**Issue by 9201314** [GoogleChromeLabs/squoosh#1226]
Can't use it. When I upload a picture then give me this error message :

Processing error: ReferenceError: WebAssembly is not defined

System version : Windows 11 Pro 22000.527

Browser version : Microsoft Edge 98.0.1108.62

**Comment by Viktova** [comment]
+1 ; NodeJS needs to be updated on Google's end I guess.

**Comment by 9201314** [comment]
> +1 ; NodeJS needs to be updated on Google's end I guess.

Microsoft Edge can't use it. But other browsers are fine. Like Chrome or Firefox.

**Comment by MadeBaruna** [comment]
Turning on "Enhance your security on the web" (https://support.microsoft.com/en-us/microsoft-edge/enhance-your-security-on-the-web-with-microsoft-edge-b8199f13-b21b-4a08-a806-daed31a1929d) feature on Edge caused this.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
