### ISSUE TITLE
Bug  - (Image Compression Squoosh.app ) `Processing error: RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info`

### ISSUE THREAD

**Issue by cliffordfajardo** [GoogleChromeLabs/squoosh#1227]
## Describe the bug
When attempting to compress a png file that is 3.6mb large with 15000 × 19400 dimensions, squoosh web app on all major browsers is failing with the following error:

```
Processing error: RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
```

## To Reproduce
1. Attempt to compress this png file that is 3.6mb large
please visit the image URL and save this png image (15000 × 19400): https://www.fullcontextdevelopment.com/img/roadmap/desktop/code-to-money-roadmap-v.0.0.1-lq.png
Preview of image
<img width="661" alt="CleanShot 2022-03-16 at 02 34 40@2x" src="https://user-images.githubusercontent.com/6743796/158560327-8898d019-604d-4e02-85c5-3ae08ea9ed30.png">

2. Upload it to squoosh web app
3. Squoosh will error and report the following error on Chrome, Safari and Firefox

```
Processing error: RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
```
![image](https://user-images.githubusercontent.com/6743796/158559556-ed551a3a-d42b-49e6-9af5-704b631cc9cd.png)
<img width="1782" alt="CleanShot 2022-03-16 at 02 37 41@2x" src="https://user-images.githubusercontent.com/6743796/158560844-673c8b0d-21c0-4681-b059-6284ecd87247.png">

**Expected behavior**

**Version:**
 - OS w/ version: Mac OS Big Sur 11.6.5
 - Browser w/ version: 
     - Chrome: 99.0.4844.51 
      - Safari: 15.3 
      - Firefox Dev Edition: 99.0b4 (64-bit)
 - Node version: N/A using Squoosh web app

**Comment by erikyo** [comment]
Found this issue by searching generically on the web because i had the same exact message in browser console with a forked version of squoosh that I am working on, rebuilt in [webpack that works without node](https://erikyo.github.io/squoosh/)... I guess these kind of issues are related to codecs and not to squoosh, I solved it by recompiling libAvif codec with version [0.9.3](https://github.com/AOMediaCodec/libavif/archive/refs/tags/v0.9.3.tar.gz) that seems to work very well, even with large images (tested > 16mb) and looks quite faster that before.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
