### ISSUE TITLE
how can i integrate squoosh to a blazor webassembly api

### ISSUE THREAD

**Issue by janof1** [GoogleChromeLabs/squoosh#1236]
hello friends I hope not to disturb, I would like to know if there is any way to integrate the Squoosh API in my Blazor WebAssembly API. 
I appreciate any help you could give me.
thank you very much

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
