### ISSUE TITLE
Available file extension

### ISSUE THREAD

**Issue by kota-yata** [GoogleChromeLabs/squoosh#1245]
**Is your feature request related to a problem? Please describe.**
I tried to use libsquoosh for optimizing images that are the same hierarchy as non-image files (i.e. js files or plane text files). I wonder if there is a list of available file extensions to which I can refer in order to eliminate those non-image files from target files.

**Describe the solution you'd like**
I guess listing available file extensions in README is enough for my usage.

Thank you.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
