### ISSUE TITLE
'has an unsupported format' happen to specific avif image

### ISSUE THREAD

**Issue by JolyneAnasui** [GoogleChromeLabs/squoosh#1249]
**Describe the bug**
i have an test.avif converted by [Convertio](https://convertio.co/), i want to use squoosh-cli to compress it but get an error
```
$ squoosh-cli --avif '{}' test.avif
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a 
catch block, or by rejecting a promise which was not handled with .catch(). 
The promise rejected with the reason "test.avif has an unsupported format".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```
but it work when the image is converted by squoosh itself
```
$ squoosh-cli --avif '{}' test1.png
1/1 √ Squoosh results:
 test1.png: 770.92KB
  └ test1.avif → 16.93KB (2.20%)

$ squoosh-cli --avif '{}' test1.avif
1/1 √ Squoosh results:
 test1.avif: 16.93KB
  └ test1.avif → 15.42KB (91.0%)
```

**To Reproduce**
1. convert a png image to avif using [Convertio](https://convertio.co/)
2. run `squoosh-cli --avif '{}' test.avif` 

**Version:**
 - OS w/ version: Windows10
 - Browser w/ version Chrome 100.0.4896.127
 - Node version: 16.14.2
 - npm version: 8.5.0

is there any difference between the avif image converted by Convertio and Squoosh?

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
