### ISSUE TITLE
CLI misses the -V option

### ISSUE THREAD

**Issue by JalinWang** [GoogleChromeLabs/squoosh#1254]
The CLI 0.72 has no -V option
![image](https://user-images.githubusercontent.com/20621784/173169755-5047eab0-3e70-4fd5-a994-77005fcc9362.png)

![image](https://user-images.githubusercontent.com/20621784/173169695-814ac9a2-18f0-43a5-ac2b-fc4343e65d91.png)

However, -V has been claimed in the README.
![image](https://user-images.githubusercontent.com/20621784/173169742-e58c46d4-6481-48e4-8c03-4c0c53df996e.png)

I'm wondering whether I need to open a PR to fix the README or support -V.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
