### ISSUE TITLE
@squoosh/lib is out of date on npm compared to `dev`

### ISSUE THREAD

**Issue by devinmatte** [GoogleChromeLabs/squoosh#1265]
**Is your feature request related to a problem? Please describe.**
`@squoosh/lib` is at `0.5.0` in the `dev` branch but the latest published version on npm is `0.4.0`.

**Describe the solution you'd like**
Publish a newer version of `@squoosh/lib`

**Additional context**
Was running into issues using the package on node `18.6.x`, not sure if that's related to the package or not, but figured the fact that the package was over a year old on NPM and a newer version was available inside the repo wouldn't help. I can dig deeper into my issue but wanted to get this issue up now to ensure the maintainers were aware the published package was behind by a while.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
