### ISSUE TITLE
[CLI] Crash when given invalid parameters

### ISSUE THREAD

**Issue by wojtekmaj** [GoogleChromeLabs/squoosh#1267]
**Describe the bug**

Running a squoosh-cli command with (seemingly) invalid parameters results in a crash.

**To Reproduce**
1. Execute e.g. `squoosh-cli *.jpg --mozjpeg --resize 960 --output-dir ./output`

**Expected behavior**
A clear message on what I'm missing, e.g. "expected 'mozjpeg' param to have value"

**Version:**
 - OS w/ version: [e.g. iOS 12] macOS 12.4
 - Browser w/ version [e.g. Chrome 70] n/a
 - Node version: [e.g. 10.11.0] 16.14.2
 - npm version: [e.g. 6.4.1] 8.15.0

**Additional context, screenshots, screencasts**

<img width="977" alt="Zrzut ekranu 2022-07-27 o 09 46 14" src="https://user-images.githubusercontent.com/5426427/181191385-a6eb6994-805e-4b36-a668-75c87aec9464.png">

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
