### ISSUE TITLE
squoosh-cli killed without error log

### ISSUE THREAD

**Issue by flowhub-team** [GoogleChromeLabs/squoosh#1270]
![image](https://user-images.githubusercontent.com/99722769/183243964-332b6a0c-a7ac-418c-8022-f8e813936b42.png)

**Comment by sefirosweb** [comment]
Same for me, I tried CLI and LIB and both i have samme issue

Maybe the computer no have enough resources? or the picture is to huge?

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
