### ISSUE TITLE
Specific AVIF file isn't supported using @squoosh/lib but is supported on https://squoosh.app/

### ISSUE THREAD

**Issue by oz-tagbox** [GoogleChromeLabs/squoosh#1289]
**Description**
a specific AVIF file isn't supported using @squoosh/lib 
when trying to decode we get 'Binary blob has an unsupported format' error message
but when uploaded to https://squoosh.app/ is supported

trying to decode and work on other avif files **works** using @squoosh/lib 

**To Reproduce**

import { ImagePool } from '@squoosh/lib';
const imagePool = new ImagePool();

const { Body } = await s3.getObject({Key: key, Bucket: bucket}).promise();
 const image = imagePool.ingestImage(Body);
 await image.decoded;
 
then we get the error: 'Binary blob has an unsupported format'

**Expected behavior**
The file to be decoded

**Version:**
 - OS w/ version: iOS 12
 - Node version: v12.22.3
 - npm version: 6.14.13
 - @squoosh/lib: 0.4.0

**Is your issue related to the quality of image compression?**
yes
- Original image s3 public location: https://s3.eu-west-1.amazonaws.com/tagbox.public.bucket/space-1-HDR-optimized.avif

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
