### ISSUE TITLE
Tutorial building squoosh for browser / integrating with other react framework (Next.js)

### ISSUE THREAD

**Issue by Mandelag** [GoogleChromeLabs/squoosh#1298]
My user story:
 - Existing react project developer want to integrate squoosh library on their web page, to take advantage of image compression capabilities. But "@squoosh/lib" cannot be imported directly to browser app, since have dependencies (such as `fs`). 
 - Current build system is specific to this project. My case uses `Next.js`, and there is no beginner friendly tutorial to integrate them (If I'm able to, I'll share)
 - I'm beginner in javascript build system

Proposed solution:
- Tutorial
- Make the @squoosh/lib support browser environment out of the box for any other react project

Squoosh is really great library. I think it will increase this library adoption more If we make it easier to integrate with other framework

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
