### ISSUE TITLE
global navigator   sass and @squoosh/lib in web

### ISSUE THREAD

**Issue by ErKeLost** [GoogleChromeLabs/squoosh#1300]
**Describe the bug**
Does not work properly when sass is used with @squoosh/lib

**To Reproduce**
1. [unplugin-imagemin](https://github.com/ErKeLost/unplugin-imagemin)
2. pnpm install 
3. cd playground
4. pnpm build

**Expected behavior**
 ### Normally, it performs very well.

![image](https://user-images.githubusercontent.com/66500121/203934552-9b02e896-a833-462c-a514-0502158b51b0.png)

As long as there is sass in the package of the project, like **import squoosh/lib** and **import sass** the instantiation of ImagePool will cause the sass processor to report an error. Is there any solution? 

Add sass to the style attribute type
![image](https://user-images.githubusercontent.com/66500121/203935489-d01f88c9-14f8-44d7-a842-3a927298dcb2.png)

![image](https://user-images.githubusercontent.com/66500121/203933668-8eb92c2b-7d97-4768-987f-74dfb9729021.png)

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.

**Comment by ErKeLost** [comment]
> 不幸的是，由于一些人离开了团队，以及当前经济环境导致的人员配备问题 (ugh)，CLI 和 libsquoosh 包不再积极维护。我知道这很糟糕，但根本没有时间和人来处理这个问题。如果社区中的任何人想要分叉它，我都会祝福你。squoosh.app网络应用程序将继续得到支持和改进[。](https://squoosh.app/)

Thank you very much for your reply. I can solve the problem in this way at present.

`delete globalThis.navigator;`

![image](https://user-images.githubusercontent.com/66500121/210373257-f4473d97-94ed-47e4-9365-9aa97a57bfa3.png)
