### ISSUE TITLE
wee_alloc used by resize is unmaintained and has a memory leak

### ISSUE THREAD

**Issue by xfalcox** [GoogleChromeLabs/squoosh#1301]
Per https://github.com/advisories/GHSA-rc23-xxgq-x27g, the wee_alloc optional-but-default dependency of the resize is not maintained anymore, plus has an unbounded memory leak.

This triggered some automatic vulnerability scanners for projects using Squoosh, so it may be a good idea to evaluate using the default allocator / some other library.

**Comment by surma** [comment]
Our wasm modules are fairly short lived and contained in the wasm sandbox, so I don't think this is a concerning problem here for now, and the smaller file size matters

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
