### ISSUE TITLE
squoosh-cli resize --webp error

### ISSUE THREAD

**Issue by charliecen** [GoogleChromeLabs/squoosh#1303]
```sh
squoosh-cli --resize '{"enabled":true,"width":96,"height":95,"method":"lanczos3","fitMethod":"stretch","premultiply":true,"linearRGB":true}' --webp '{"quality":50, "method":4,"sns_strength":50,"filter_strength":60,"filter_type":1,"segmen
ts":4,"pass":1,"show_compressed":0,"preprocessing":0, "autofilter":0, "partition_limit":0, "alpha_compression":1, "alpha_filtering":1, "alpha_quality":100,"lossless":0}' uphjqljv.webp
0/1 ⠇ ▐╌╌╌╌╌╌╌╌╌╌▌ Decoding...
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Cannot read properties of null (reading 'data')".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v17.9.0
```

Use the squoosh app to compress successfully.  But the command cannot be compressed successfully
![20221208-173336](https://user-images.githubusercontent.com/6268321/206410836-dc81875a-fbc5-4d68-bdc2-80b34ea06d08.png)

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
