### ISSUE TITLE
Safari + OxiPNG gives "Processing error: ReferenceError: Can't find variable: Worker"

### ISSUE THREAD

**Issue by lpar** [GoogleChromeLabs/squoosh#1324]
**Describe the bug**
On the current live site, attempting to use OxiPNG is giving me "Processing error: ReferenceError: Can't find variable: Worker".

Works in Firefox, so probably something to do with Apple's half-assed implementation of Web Workers.

**To Reproduce**
1. Go to squoosh.app with Safari.
2. Drag-drop a macOS Screenshot PNG into window.
3. Select OxiPNG compression.
4. See error.

**Expected behavior**
Compressed PNG.

**Version:**
 - OS w/ version: macOS Ventura 13.1
 - Browser w/ version: Safari 16.2

**Comment by surma** [comment]
Can confirm in Safari 16.2 (18614.3.7.1.5) on Ventura 13.1 (22C65). 

AVIF and JXL also throw the same error. Seems like any codec that makes uses of Wasm threads is currently broken in Safari.

**Comment by surma** [comment]
It seems that Safari shipped Wasm Threads in Stable, but not support for Nested Workers (which we need since we run our Wasm in workers). Safari TP has support for nested workers and the error does not appear there for me.

<img width="1250" alt="Screenshot 2023-01-08 at 18 26 16" src="https://user-images.githubusercontent.com/234957/211212646-d1e5d30d-5bfe-45d6-b692-bffb4fdd329b.png">

**Comment by jakearchibald** [comment]
PR up https://github.com/GoogleChromeLabs/squoosh/pull/1325
