### ISSUE TITLE
Fix css.d.ts double-build issues

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#251]
It'll half our deploy time 😄.

The answer is to use https://github.com/Quramy/typed-css-modules rather than (or in addition to) the webpack plugin.

**Comment by fstanis** [comment]
I tried playing around with this, but it seems https://github.com/Quramy/typed-css-modules doesn't quite work since it doesn't support Sass and tackling that is going down the rabbit hole.

I'm not quite clear why `typings-for-css-modules-loader` is causing this. My understanding is that it's generating the typings asynchronously and TS isn't waiting for it? Also, possibly unrelated, but [there's an issue claiming it's incompatible with webpack 4 and css-loader 1.0 which we use](https://github.com/Jimdo/typings-for-css-modules-loader/issues/77).

**Comment by egorkaru** [comment]
> it doesn't support Sass and tackling that is going down the rabbit hole.

just replace
`        loader: 'typed-css-modules-loader',
`
with
`        loader: ['typed-css-modules-loader', 'sass-loader'],
`

**Comment by fstanis** [comment]
That's already working that way. The idea here (I think) was to try to replace `typed-css-modules-loader` in webpack with `typed-css-modules` which is an (unrelated?) CLI that does a similar thing and have it be a separate step in the build. However, because this CLI doesn't support Sass, we'd also need to use the Sass CLI to get that to work, making it too convoluted as a solution IMO.

**Comment by jakearchibald** [comment]
I managed to get it working https://github.com/GoogleChromeLabs/squoosh/pull/350. Bypassed the webpack plugin entirely, but that's mostly because I don't understand webpack plugins.
