### ISSUE TITLE
Electron app version

### ISSUE THREAD

**Issue by aakreidler** [GoogleChromeLabs/squoosh#355]
It would be nice to have an Electron app version of Squoosh to run natively.

Also, it would be nice to have the ability to work with multiple files (#301) in this native version.

I love Squoosh because it can convert between formats while showing the size and quality impact. I think it could be even more powerful as a native app with support for drag and drop, opening files, and a multi-file workflow. Keep it up!

BTW, if anyone knows another native app that can convert between _and_ compress in multiple image formats, let me know.

**Comment by jakearchibald** [comment]
Why does it need to be an Electron app?

**Comment by jakearchibald** [comment]
Closing. Feel free to reopen with more info.

**Comment by ronjouch** [comment]
@jakearchibald I'm not the original poster, but I was looking for something like it too, so here's my input.

1. I'd love an offline version of the tool. Currently I do my image crushing with a set of pngquant and guetzli/mozjpeg scripts. But (as you know), an interactive UI helps fine-tune parameters. The closest I know is GIMP/Photoshop's "export with preview" screen, but your UI is better.
2. So I'd like to use Squoosh more, which is exactly that: a great UI to fine-tune parameters.
3. But it feels weird to have to open a browser to do something fundamentally offline. Service workers would be *better*, as it could enable offline usage, but to me it still feels weird to do it in a browser.

→ I, too, would enjoy a non-browser, offline, version of Squoosh.

Now, there's nothing *mandating* Electron, but since all the cross-platform UI work is already done using web tech, Electron seems like a reasonable choice. Passersby may utter the usual Electron heaviness profanities, then they're welcome to rewrite it in $LIGHTWEIGHT_TECH_OF_CHOICE, but a heavy Electron app to me seems better than a non-existing one.

And then even later it could be packaged by distributions, and I could just `sudo pacman -Syu squoosh` to install the standalone app and use it 🙂.

→ Maybe this issue deserves to be re-opened and rename to something like: "Package as offline, non-browser application (probably Electron)".

At any rate, thanks for your work!
