### ISSUE TITLE
Would be nice to have a button to install Squoosh

### ISSUE THREAD

**Issue by benfredwells** [GoogleChromeLabs/squoosh#358]
**Is your feature request related to a problem? Please describe.**
Some users probably don't realise they can install this app on Chrome, via Chrome's three dot menu.

**Describe the solution you'd like**
Squoosh can use the beforeInstallPrompt event to have an install button.

**Does other service/app have this feature?**
Santa Tracker, Spotify,

**Additional context**
I'm happy to add the button if the squoosh team thinks it's a good idea and can provide some UX guidance.

**Comment by benfredwells** [comment]
If I don't hear back I'll assume this is a good idea and look into adding an install button....

**Comment by benfredwells** [comment]
(Oops hit button too soon)

... So please let me know if it isn't a good idea for some reason 🙂

**Comment by jakearchibald** [comment]
Seems like a good idea. Just needs prioritised, designed, and implemented. PRs welcome as always.

**Comment by benfredwells** [comment]
FWIW I've started working on this and will hopefully have something up soon. Just wrapping my head around all this react stuff.

**Comment by gtsiolis** [comment]
This has been added in https://github.com/GoogleChromeLabs/squoosh/pull/764. Let's close this! /cc @surma 

UPDATE: Just run into https://github.com/GoogleChromeLabs/squoosh/pull/452. @benfredwells do you think it's still relevant?  If that is adding the PWA install prompt as seen in https://github.com/GoogleChromeLabs/squoosh/pull/452#issuecomment-461457210 I'd say yes. WDYT?

/cc @jakearchibald because https://github.com/GoogleChromeLabs/squoosh/pull/452
