### ISSUE TITLE
Vector scaling breaks at higher scaling values

### ISSUE THREAD

**Issue by jagij** [GoogleChromeLabs/squoosh#573]
I want to be able to convert an SVG to a PNG while blowing up the image by a large factor. 

I was not expecting the input file to be converted to an bitmap first, before any conversion has been applied. If I blow up the image by a factor of 4, suddenly I get a completely pixelised output. Since SVG is a format that scales, this is quite an unexpected result.

**Does other service/app have this feature?**
https://cloudconvert.com/svg-to-png can convert an svg to a png using some resolution. Choosing the max of 500dpi gave me the result I was looking for (more or less).

**Comment by surma** [comment]
You seem to have uncovered a weird bug :D

We do not rasterize SVG. We actually support SVG vector scaling. If you open the Squoosh logo from the home screen, you can rescale it to, let’s say, 2000x2000 and it should look pixel perfect!

<img width="1274" alt="Screenshot 2019-04-30 at 10 11 45" src="https://user-images.githubusercontent.com/234957/56951734-81b16680-6b30-11e9-9607-3e9169e83df6.png">

**BUT** for some reason, when I go further up to 4000x4000 for example, I see the scaling degrade.

<img width="1273" alt="Screenshot 2019-04-30 at 10 13 14" src="https://user-images.githubusercontent.com/234957/56951801-9d1c7180-6b30-11e9-8919-cef679cbecb1.png">

So that’s odd. We’ll investigate.

**Comment by dhpar** [comment]
This seem to happen also when zooming into the image, at least in my phone.

Couldn't inspect the code (since I'm on my phone) so not sure how this is runner in the browser but if an SVG is implemented with the img tag or background-image image (I believe) it rasterizes the SVG, but if an SVG is implemented as xml tags (ie: <SVG ...>...</SVG>) inside HTML or background-image xml tags, the image keeps it's vector form and this allows the correct scaling (amongst other SVG benefits) .

**Comment by dhpar** [comment]
Nevermind, now that I inspected code I see that this is all managed through canvas, I have no experience with canvas, I wonder if canvas is rasterizing the svg, though.

**Comment by dhpar** [comment]
[This article](https://css-tricks.com/when-to-use-svg-vs-when-to-use-canvas/) (had no idea) just made me realize that there is a difference on how an svg is rendered in a canvas.

**Comment by kosamari** [comment]
I believe this one is fixed now with V2
