### ISSUE TITLE
Make web api for squoosh

### ISSUE THREAD

**Issue by gsGabriel** [GoogleChromeLabs/squoosh#651]
Create a service that compresses and returns the compressed image according to the parameters entered

I need that haha

**Comment by ferrisbuellers** [comment]
How do you envision this web API working?

Are you thinking where you post an image to an api url with query data for compression parameters and have this api return you the compressed image?

If so I believe squoosh runs purely in the browser so a web api like the above might be unlikely or out of the scope of Google's vision for this project.

However, since it's running in JS I guess it could be possible to clone squoosh and create a node application that could do this for you.

**Comment by zyyoo** [comment]
I hope it supports API access and can quickly compress images

**Comment by surma** [comment]
We have a [CLI](https://github.com/GoogleChromeLabs/squoosh/tree/dev/cli) now!
