### ISSUE TITLE
[webpack]Cannot find module './style.scss'. error

### ISSUE THREAD

**Issue by kosamari** [GoogleChromeLabs/squoosh#66]
1. npm install
1. npm run build
1. errors in finding './style.scss'
1. npm run build again
1. -> no more error (why ???)

Error message
```
ERROR in /Users/kosamari/Code/squoosh/src/components/app/index.tsx
[tsl] ERROR in /Users/kosamari/Code/squoosh/src/components/app/index.tsx(3,24)
      TS2307: Cannot find module './style.scss'.
```

**Comment by developit** [comment]
One tip we could use in the instructions for now as a workaround is to recommend running `npm start` - it'll technically emit an error the first time, but will immediately rebuild and correct itself:

```sh
git clone 
npm install
npm start
```

It also probably makes more sense to recommend this since most people clone and want a development server, not a production app.

**Comment by surma** [comment]
Even more sneaky: Run `build` as a `postinstall`?

I’m guessing there’s no easy way to fix this, like, properly?

**Comment by developit** [comment]
@jakearchibald but only with `npm run build`, right? `webpack-dev-server` via `npm start` should always just build twice and continue.

**Comment by jakearchibald** [comment]
Hmm, I'll provide recreation steps if I run into it again.

**Comment by PaulKinlan** [comment]
https://github.com/Jimdo/typings-for-css-modules-loader/issues/33
