### ISSUE TITLE
If image.avif.enabled set to true in FF80 decoding fails

### ISSUE THREAD

**Issue by pmario** [GoogleChromeLabs/squoosh#809]
**Describe the bug**

If `image.avif.enabled` set to `true` in FF80 decoding a compressed image fails 

**To Reproduce**

 - Use FF 80 ... 
 - about:config - set `image.avif.enabled` -> true
 - select a demo image
 - left side original / right side choose: AVIF

After some time it will fail with an error message produced at **line 14 `builtinDecode`** in: https://github.com/GoogleChromeLabs/squoosh/blob/4768bc17ba7949e569753680eb5b90853d0c1ac3/src/codecs/decoders.ts#L8-L17

If `image.avif.enabled` is `false` it works.

**Comment by jakearchibald** [comment]
Thanks for the report. This might be a bug in Firefox's experimental implementation where decoding via `<img>` works fine (which is how our feature detect works), but decoding via `createImageBitmap` fails (which is how we actually get the pixels out of the image).

I'll dig in, and create a bug against Firefox if needed.

**Comment by atjn** [comment]
This is fixed in Firefox 81, check out [this bug thread](https://bugzilla.mozilla.org/show_bug.cgi?id=1443863#c19).

...although they weren't quite sure how they fixed it. If anyone can explain exactly what goes wrong in FF80, i think they would be interested in hearing about it, just so they can make sure it's not the symptom of a larger unsolved issue in Firefox.

**Comment by jakearchibald** [comment]
Firefox's AVIF support is extremely alpha right now, and isn't expected to work well (it doesn't support alpha for instance), so I'm going to close this.

We might consider fixes to work around Firefox issues if they're still there once the flag is enabled by default.

In the meantime, issues should be filed against Firefox.
