### ISSUE TITLE
Fix maskable icons

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#811]
https://squoosh.app/icon-large-maskable.png is a 404. Chrome webapks now support maskable icons, so we should get this right.

**Comment by glennhartmann** [comment]
I think this was a false alarm, actually (sorry).

First, due to copy/paste error, I mentioned https://squoosh.app/icon-large-maskable.png, but it should actually have been https://squoosh.app/assets/icon-large-maskable.png.

Second, I believe this was fixed recently in https://github.com/GoogleChromeLabs/squoosh/commit/63f607a3ead0052b4908134cedcb3f912bceab54, but I may not have seen the change on my machine yet due to an out-of-date service worker?

Anyway, seems to be working now, sorry for the false report.

**Comment by jakearchibald** [comment]
No worries!
