### ISSUE TITLE
AVIF: Expose additional options

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#831]
From https://github.com/AOMediaCodec/libavif/blob/master/apps/avifenc.c#L100

- `aq-mode` - allows the quantisation to change between segments in various ways.
- `sharpness` - as you'd imagine
- `enable-chroma-deltaq` - reduce chroma quality at 4:4:4 (actually, I don't know if it's just 4:4:4)

From Wan-Teh Chang:

---

Note that this requires building libavif with a recent version of
libaom, as opposed to the libaom version (v2.0.0) specified in
libavif/ext/aom.cmd. Also, the current tip of libavif has some decoder
changes that still need to be reviewed carefully. So don't use the
current tip of libavif in your production systems if you also use it
to decode libavif images. The encoder side of libavif is OK.

**Comment by tongyuantongyu** [comment]
Here's a suggestion: I'd like to see `denoise-noise-level` option being exposed.

From https://github.com/AOMediaCodec/libavif/commit/1809baa9ef3d6b31a12976166e36534504deb88c almost all options in libaom can be set through libavif, if built with libaom v3.0.0 or above.

Among these options, `denoise-noise-level` is a really interesting one. AV1 codec has a feature called 'grain synthesis', which uses math model to describe the characteristic of noise, and synthesize it during decoding.
`denoise-noise-level` option accepts a number between 0 and 50. When > 0, it tries to remove given level of noise from source image, meanwhile also models the removed noise, so that the noise can be added back during decoding in the 'grain synthesis' step.

This really helps compressing photos without introducing perceptual differences. The demo image `photo.jpg` is a really good example.
check the compressed files: [avif-denoise-compare.zip](https://github.com/GoogleChromeLabs/squoosh/files/6319067/avif-denoise-compare.zip)

The three files are created using `avifenc` from `libavif`, with following commands:
```bash
avifenc --min 0 --max 63 -a end-usage=q -a cq-level=33 -s 8 -y 420 --ignore-icc photo.jpg photo-normal.avif
avifenc --min 0 --max 63 -a end-usage=q -a cq-level=33 -a denoise-noise-level=50 -s 8 -y 420 --ignore-icc photo.jpg photo-denoise.avif
avifenc --min 0 --max 63 -a end-usage=q -a cq-level=33 -a denoise-noise-level=50 -s 0 -y 420 --ignore-icc photo.jpg photo-denoise-insane.avif
```

First two are matching the default settings used by sqoosh, the third is using the slowest speed to show the best size AVIF can reach under this quality.

When looking at `photo-denoise.avif` alone, it looks quite natural, and seems not compressed very much - until you compare it with original image side by side and realize that the noise, despite feels quite the same, is not matching at all. But nevertheless, it looks totally fine! Don't forget at this size, codecs are all blurring the background heavily, if not just giving up and creating some mosaic art.

**Comment by jakearchibald** [comment]
This is a good suggestion! I'll take a look

**Comment by jakearchibald** [comment]
PR https://github.com/GoogleChromeLabs/squoosh/pull/987
Demo https://deploy-preview-987--squoosh.netlify.app/

**Comment by tongyuantongyu** [comment]
This looks great! I forgot to mention that denoise-noise-level should only apply to color sub-image, but you figured that out.

**Comment by jakearchibald** [comment]
Haha yeah, after creating some invalid AVIFs 😀

**Comment by eclipzzze** [comment]
What do you mean by "sub-image"? I try to use "-a denoise-noise-level=50" with libaom 3.0.0 but I get "ERROR: Failed to encode image: Invalid codec-specific option"?

**Comment by jakearchibald** [comment]
Closing this, as these changes shipped
