### ISSUE TITLE
[CLI] Consider displaying a warning when output format(s) not specified

### ISSUE THREAD

**Issue by donmccurdy** [GoogleChromeLabs/squoosh#834]
**Describe the bug**

When running the CLI without specifying an output target, the command hangs for a bit and appears to do some work, but finally exits without output. After checking the current directory and the directory of the input file I was able to convince myself that I'd missed something, and then realized I'd need to specify additional options to get output, but it'd be useful to have the tool provide a warning directly in this case.

**To Reproduce**
1. Run the cli with options `-d ~/Desktop ~/Desktop/test.png`
2. No output is created

**Expected behavior**

Ideally, a warning should appear explaining that at least one of the target output options are required.

**Version:**
 - OS w/ version: macOS 10.15.6
 - Node version: v14.14.0

Thanks!

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.

**Comment by donmccurdy** [comment]
Thanks @jakearchibald — I appreciate the update. I use and share the web app all the time.  Really grateful for your (and the team's) work on this project and on other improvements across the web.
