### ISSUE TITLE
[CLI] Consolidate rollup plugins between PWA and CLI

### ISSUE THREAD

**Issue by surma** [GoogleChromeLabs/squoosh#882]

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
