### ISSUE TITLE
[CLI] Add support for SVG input

### ISSUE THREAD

**Issue by surma** [GoogleChromeLabs/squoosh#884]

**Comment by fernap3** [comment]
I'd like to +1 this and just drop a use case here.

We ship a web app with the ability for clients to customize whether or not it serves SVG or PNG icons. This means we ship SVG and PNG versions of the same icons; so the use case for us is to generate the PNG versions at build time from the SVGs.

**Comment by fernap3** [comment]
Design question: should it be a goal to be able to take an input SVG and vector-resize to any arbitrarily-sized raster format like PNG?  Or would having a new "SVG" decoder return a bitmap at the intrinsic height and width of the SVG be a suitable initial goal?

Also, I see there are a couple NPM modules that will rasterize SVG. Are there any license concerns specific to this project that are worth noting?  If it's not clear, I'm investigating an implementation. :)

**Comment by surma** [comment]
Just like the web app, resizing should happen _before_ rasterization. 

Re licensing: Anything that is Apache-2.0 or MIT should be no problem. Other licenses _might_ work, but will be look at on a case-by-case basis.

**Comment by fernap3** [comment]
Just brain dumping some progress here.  I was able to implement an SVG decoder using Puppeteer. But I'm not sure if it's going to be acceptable to make users incur the Chromium download just to use the CLI. Maybe we could conditionally download if we detect SVG input.  So this may not be the best solution, but it was quick to implement and also means SVG rasterization happens the exact same way that it does in the web app.

Other options:
* Try to get [node-canvas](https://github.com/Automattic/node-canvas) to work. I ran into some rollup issues since node-canvas uses native Node (`.node`) modules and the build was choking on that.
* Find some other library and compile to wasm. This will probably be substantially more work.

![image](https://user-images.githubusercontent.com/1057057/103251772-44762b00-4948-11eb-8b0e-2d05d41dc33e.png)

**Comment by surma** [comment]
Yeah, using Puppeteer is not going to be an acceptable solution tbh :D

So Chromium uses [Skia] for painting. Skia has been ported to WebAssembly in the [CanvasKit] project. I wonder if that has a way to paint SVGs?

[Skia]: https://skia.org
[CanvasKit]: https://skia.org/user/modules/canvaskit

**Comment by tomByrer** [comment]
Sharp translates SVG-to-___ just fine:
https://techsparx.com/nodejs/graphics/svg-to-png.html
API is very easy also, gives me the dot-notation-fuzzies of when I used jQuerry
https://sharp.pixelplumbing.com/api-constructor

**Comment by fernap3** [comment]
Thanks for the resource @tomByrer! I'll take a look

**Comment by kosamari** [comment]
Housekeeping Note (ignore me !) : we consider this may be complex and long-running project. We may need to break down tasks more.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
