### ISSUE TITLE
[CLI] Crop/extract area

### ISSUE THREAD

**Issue by tmjoen** [GoogleChromeLabs/squoosh#901]
First of all, thanks for this excellent project and for creating a CLI version!

Currently I've always prefered to do my image processing on my own server instead of offloading it to another service. For this I've used libvips/sharp-cli which has been a much better experience than ImageMagick/GraphicsMagick.

The BIG drawback with libvips/sharp-cli is the enormous compilation steps. To get webp/mozjpeg/png compression it is close to 30 minutes of compiling on my server for a new version.

**Describe the solution you'd like**
Your new Squoosh CLI seems to almost fit the ticket for my needs, it only lacks a way to flexibly crop images. I really like how they do it with `sharp-cli`: You resize, then extract the area you want -> `sharp resize <width> [height] extract <top> <left> <width> <height>`

**Does other service/app have this feature?**
Sharp/sharp-cli (an excellent source of inspiration for all things image processing!) -> https://github.com/vseventer/sharp-cli

**Comment by surma** [comment]
We have a better crop feature in the works, that will also get ported to the CLI. So #soon :)

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
