### ISSUE TITLE
cli mode, mozjpeg changed direction in some picture

### ISSUE THREAD

**Issue by aizuyan** [GoogleChromeLabs/squoosh#928]
decode and encode the below picture, the result change the direction of the original picture
`squoosh-cli ~/js/bit-img/dist/nk2.jpg  --mozjpeg`

![nk2](https://user-images.githubusercontent.com/6612863/103400515-5e01b780-4b80-11eb-90df-991c972212ea.jpg)

original pic and result pic:
![截屏2020-12-31 下午3 59 30](https://user-images.githubusercontent.com/6612863/103400736-34955b80-4b81-11eb-9249-909eec142862.png)

**Comment by surma** [comment]
This is most likely because the original picture is _actually_ sideways but contains EXIF data that prompts most UIs to display it in a rotated fashion. We currently ignore and strip EXIF data and — with compression being the main focus of Squoosh — have no intention of changing that. 

Gonna close this. Please feel free to reopen if you disagree or think there’s a different underlying cause.
