### ISSUE TITLE
Please add ability to disable antialiasing (checkbox)

### ISSUE THREAD

**Issue by rootext** [GoogleChromeLabs/squoosh#950]
**Is your feature request related to a problem? Please describe.**
Squoosh is a great tool but it is almost impossible to compare tiny images because of antialiasing (for zoom 500% and higher)

**Describe the solution you'd like**
Add ability to disable antialiasing (checkbox)

**Does other service/app have this feature?**
I don't know

**Additional context**
With antialiasing enabled
![image](https://user-images.githubusercontent.com/1571180/105550917-fd255500-5ccf-11eb-9ff5-3730b44b0c6e.png)
With antialiasing disabled
![image](https://user-images.githubusercontent.com/1571180/105551186-6907bd80-5cd0-11eb-8e06-e36a4f2997af.png)

**Comment by jakearchibald** [comment]
What are you looking to compare? We went with interpolation by default as that's how browsers will render the image when scaled.

Not against adding an option for this, just want to hear more about the use-case.

**Comment by rootext** [comment]
I am looking to compare original image with optimized one on the right side. I want to  clearly see all optimization artifacts.
Yes, browser also uses interpolation but I will not scale an image 500% on a wep page. Usually it's 1:1 for small ui images.

**Comment by jakearchibald** [comment]
Yeah, that's fair. Thanks for the clarification.

**Comment by myakura** [comment]
Yes. I was using squoosh to optimize a 32x32 PNG favicon the other day and thought it'd be cool to have such option too. (I set `image-rendering: pixelated` to the canvas via devtools to disable it.)

**Comment by tomByrer** [comment]
> set `image-rendering: pixelated` to the canvas via devtools to disable it

Ah cool thanks; I was wondering if that or `crisp-edges` would work.

Suggested PNG test images: http://www.schaik.com/pngsuite/pngsuite_siz_png.html

My test case: I find that AVIF tends to wash out colors (always adds luminance to brighter parts).

Alternate use cases: testing if more aggressive compression can be used if the various [`image-rendering`](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering) tags are or aren't used.

**Comment by kasperkamperman** [comment]
Another use case: 
I'm using Squoosh to teach about image compression. I wanted do demonstrate and make a practicum around the loss of color and precision with certain formats. 
Since I'm in a gaming course I thought it was good to show it with some pixel art. But with interpolation on, 
the original doesn't look anymore like the "real" original (like viewed in Photoshop zoomed in the same level). 

It might even be interesting to show a pixel grid like Photoshop does (not a must have though). 

**Squoosh 2000%**

![Screenshot 2021-03-27 at 20 25 51](https://user-images.githubusercontent.com/1760616/112732605-3c278f00-8f3b-11eb-8af6-f502655a6a91.png)

**Photoshop 2000%**

![Screenshot 2021-03-27 at 20 33 07](https://user-images.githubusercontent.com/1760616/112732696-c5d75c80-8f3b-11eb-9154-c8e8b5c7deff.png)

**Original PNG for reference**

![cyberpunk-street-orignal](https://user-images.githubusercontent.com/1760616/112732625-4f3a5f00-8f3b-11eb-93bd-85953492521d.png) 
(_Artwork created by Luis Zuno (@ansimuz)_)

**Comment by tomByrer** [comment]
Seems according to [CSS-Tricks ](https://css-tricks.com/almanac/properties/i/image-rendering/)(updated 2020-08) that `crisp-edges` & `pixelated` may act differently in Firefox vs Chrome.

@kasperkamperman I'm looking up how [AVIF may shift colors](https://github.com/GoogleChromeLabs/squoosh/issues/960#issuecomment-811880408).  I also made some test images; let you know once the repo goes public.

**Comment by kosamari** [comment]
Merging this to #1087
