### ISSUE TITLE
[CLI] Increment suffix when using -s

### ISSUE THREAD

**Issue by breakdancingcat** [GoogleChromeLabs/squoosh#955]
**Is your feature request related to a problem? Please describe.**
When testing compression options, I want to run Squoosh multiple times to compare images from my desktop. Squoosh currently overwrites the original file.

**Describe the solution you'd like**
Add an increment to the file name (+i) when using -s with no parameters

**Does other service/app have this feature?**
Default behavior when saving a file with the same name on most platforms

**Comment by tomByrer** [comment]
You could create your own suffix programmatically; [example[(https://github.com/GoogleChromeLabs/squoosh/issues/934#issuecomment-782964138)

**Comment by kosamari** [comment]
adding @surma to weigh in on if we should add this option or should be fixed in userland.

**Comment by surma** [comment]
I am not sure I want the auto-increment. But I think we should error when the CLI is about to overwrite the input file, unless an `--overwrite` flag or something is defined.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
