### ISSUE TITLE
AVIF compression performance (takes minutes)

### ISSUE THREAD

**Issue by laukstein** [GoogleChromeLabs/squoosh#958]
In https://squoosh.app/editor it takes a long minutes till AVIF compression finishes, please make it respond quickly.

**Comment by surma** [comment]
Which browser are you using? The AVIF encoder is notoriously slow, so there is not much we can do. But in Chrome we can at least use WebAssembly Threads to make it faster.

**Comment by laukstein** [comment]
Latest Chrome on up to date Windows 10.

**Comment by trych** [comment]
I have the same issue. So just to be clear, even in Chrome, with a large image an default settings (effort: 2) it is expected for it to take minutes, because the AVIF codec itself is just that slow. Correct?

Edit: It has been running for more than half an hour now. I have no frame of reference, how long it is supposed to take, but this seems highly unlikely to me. Is there any way for me to check, if it is still doing something (apart from the spinner)?

Edit 2: Nope, when I copy the CLI command to the clipboard and use that, the conversion is done in like 15 secs. So there must be something going wrong in the web app. :/

**Comment by surma** [comment]
@trych That’s an interesting find! Half an hour is definitely too long for any reasonable sioze.

Is it possible to provide an image and the CLI invocation that you used?

**Comment by trych** [comment]
Certainly.
[Image that I used](https://hannahbohnen.de/media/pages/placeholder/0038b07d42-1614682860/tank_schaum.jpg)

And the CLI invocation:

```
npx @squoosh/cli --resize '{"enabled":true,"width":1710,"height":1140,"method":"lanczos3","fitMethod":"stretch","premultiply":true,"linearRGB":true}' --avif '{"minQuantizer":33,"maxQuantizer":63,"minQuantizerAlpha":33,"maxQuantizerAlpha":63,"tileColsLog2":0,"tileRowsLog2":0,"speed":8,"subsample":1}'
```

(in the UI it's basically just setting the Format to AVIF, the size to 25% and leaving everything else at its defaults).

**Comment by trych** [comment]
Also regarding compression strategies, a quick side question: In cases like this with a huge source image, is it generally recommended to do the compression from the source whenever possible? Or would it make more sense to first reduce the image in resolution with little compression and then do the final compression from this smaller sized image?

**Comment by surma** [comment]
The resize operation in Squoosh runs _before_ compression, so that’s already happening automatically.

**Comment by trych** [comment]
Ah, okay. I thought that maybe resizing was part of the compression step itself, so that maybe the codec could better predict how to visually translate a large source area to a smaller target area while using the current compression settings.

But if the resizing happens before the compression then there is definitely something going wrong, if the AVIF compression takes forever in this case.

**Comment by jakearchibald** [comment]
I think this is a bug. Investigating…

**Comment by jakearchibald** [comment]
Yeah, this is a bug.

1. Open red panda image
2. Resize width to 1500
3. Select AVIF

It never seems to finish. However, if I alter the source so it always uses the single threaded encoder, it finishes in around 10 seconds. So yeah, this is a bug in our multi-threaded path.

The issue also impacts Firefox, but it doesn't impact Safari (because it doesn't support multi-threaded wasm).

@RReverser do you have time to look at this? If not, I propose we remove the multi-threaded encoder for now. WDYT @surma?

**Comment by surma** [comment]
Interesting! Yeah happy to disable the multi-threaded encoder until @RReverser or me can take a look why the multithreaded encoder is misbehaving.

**Comment by jakearchibald** [comment]
Cool, I'll sort that out tomorrow.

**Comment by RReverser** [comment]
Very interesting. I can take a look tomorrow, yeah.

**Comment by jakearchibald** [comment]
I've removed the multithreaded AVIF encoder from live (7f6ee3204f05689a6df8befd9c87bb4570b4a161) while @RReverser investigates.

Thanks for reporting @laukstein @trych! Things should be faster now, and will get even faster once @RReverser tracks down the multithread issue.

**Comment by RReverser** [comment]
Interesting, I guess out resizing output throws the codec on a slow path somehow.

It's definitely faster without resizing - e.g. for red panda image it takes 15s without threads and 10s with threads on my machine.

**Comment by jakearchibald** [comment]
Whoa, you're right, if you switch to "Browser high quality" resizing (which doesn't use our wasm resizer), it works.

**Comment by jakearchibald** [comment]
No resize, but "reduce palette", AVIF seems problematic too. It eventually fails with "memory access out of bounds".

**Comment by jakearchibald** [comment]
> if you switch to "Browser high quality" resizing (which doesn't use our wasm resizer), it works.

This isn't due to wasm vs not wasm. Some images cause the bug, some images don't. But it's super weird that two very similar same-size versions of the red panda behave differently.

It's definitely down to the pixel data itself.

**Comment by RReverser** [comment]
Just to provide an update here: I found the underlying issue and working on a proper fix.

**Comment by RReverser** [comment]
This should be properly fixed now, multithreaded AVIF is live again.
