### ISSUE TITLE
[CLI] Png, WebP to Avif - BindingError: Cannot pass non-string to std::string

### ISSUE THREAD

**Issue by Hahlh** [GoogleChromeLabs/squoosh#959]
**Describe the bug**
Using squoosh-cli and trying to convert a png / webp to avif. I tried to alter the input options like passing the file name as a string, but to no avail. Converting from png to webp works without errors with the same input options pattern that is described below.

The command starts sucessfully (apparently successful decoding), but throws an error directly after starting the encoding process:

```
vvvv@maschine24 ~/Documents/KuttBjoern $ squoosh-cli --avif auto Kattbljor_Flip_v011_0000.webp 
0/1 ⠏ ▐▨▨▨▨▨╌╌╌╌╌▌ Encoding (4 threads)
 Kattbljor_Flip_v011_0000.webp: 241.68KBBindingError: Cannot pass non-string to std::string
    at BindingError.<anonymous> (/home/vvvv/.npm-packages/lib/node_modules/@squoosh/cli/build/index.js:7:268883)
    at new BindingError (eval at Tb (/home/vvvv/.npm-packages/lib/node_modules/@squoosh/cli/build/index.js:1:1), <anonymous>:2:34)
    at R (/home/vvvv/.npm-packages/lib/node_modules/@squoosh/cli/build/index.js:7:269189)
    at Object.toWireType (/home/vvvv/.npm-packages/lib/node_modules/@squoosh/cli/build/index.js:7:277225)
    at Object.decode (eval at Xa (/home/vvvv/.npm-packages/lib/node_modules/@squoosh/cli/build/index.js:1:1), <anonymous>:5:26)
    at decode (/home/vvvv/.npm-packages/lib/node_modules/@squoosh/cli/build/index.js:7:537777)
    at /home/vvvv/.npm-packages/lib/node_modules/@squoosh/cli/build/index.js:7:536028
    at async binarySearch (/home/vvvv/.npm-packages/lib/node_modules/@squoosh/cli/build/index.js:7:535409)
    at async autoOptimize (/home/vvvv/.npm-packages/lib/node_modules/@squoosh/cli/build/index.js:7:535909)
    at async encodeFile (/home/vvvv/.npm-packages/lib/node_modules/@squoosh/cli/build/index.js:7:537821)
Worker error:  Error [RuntimeError]: abort(BindingError: Cannot pass non-string to std::string). Build with -s ASSERTIONS=1 for more info.
    at process.w (/home/vvvv/.npm-packages/lib/node_modules/@squoosh/cli/build/index.js:7:376640)
    at process.emit (events.js:326:22)
    at processPromiseRejections (internal/process/promises.js:209:33)
0/1 ⠹ ▐▨▨▨▨▨╌╌╌╌╌▌ Encoding (4 threads)
 Kattbljor_Flip_v011_0000.webp: 241.68KB

```

After the error has occured, the command just continues to run the encoding step (presumably) indefinitely. I let it run for something like 10 minutes without success. A verbose option would be nice.

**Version:**
 - OS w/ version: 5.10.7-3-MANJARO, DE Cinnamon 4.8.6, bash 
 - Node version: v12.20.1
 - npm version: 6.14.11

**Additional context, screenshots, screencasts**

```npx @squoosh/cli --avif auto <file>``` acts identically.

On a side note:
```npx @squoosh/cli --avif <file>``` throws the error "error: missing required argument 'files'" , which is either not accurate or an error on my side. 

Thank you for the awesome work you do!

Edit1:

I also would like to mention, that on the webapp (vanilla Chrome Version 88.0.4324.150 (Official Build) (64-bit) / Firefox 85.0.1 (64-bit))
, the conversion to avif also runs indefinitely without finishing while other conversion run fine, but without throwing an error of course. Could this hint at a missing dependency on my side? Could additional debugging info be outputted to the browser console to make issues like this more transparent?

Edit2:

Are there other utils I should test the conversion with to exclude some possible error sources?

**Comment by spayton** [comment]
I got the same error when using auto as stated in help text.  On win10 it needed single quotes, ie change it to 'auto'

Regarding your side note, it's because the command is ambiguous, --avif has an optional config which follows after the --avif flag, it is using your <file> as that config.  You can explicitly terminate the option input with a double hyphen, as follows

`npx @squoosh/cli --avif -- <file>`

**Comment by Hahlh** [comment]
Hey @spayton!

Thanks for jumping in.

Unfortunately wrapping it in single quotes didn't help and it still produced the same error. 

But using -- instead of auto did!

**Comment by spayton** [comment]
Hi, yeah, sorry, I think I was a bit premature then, I carried on playing with it, and whilst adding the single quotes stopped the error it wasn't doing a full auto run.  After a bit more playing it seems it's just the --avif target that's bust, which was the only one I was initially trying.  Using plain auto unquoted works fine for the other targets.  So, I'd say that this is still a problem.

**Comment by Hahlh** [comment]
Yes, it is still a problem, but successful conversion can be done if auto is avoided and -- is added. 
But I should probably not close this, if the problem persists, that's right.

Reopening.

**Comment by spayton** [comment]
I can see why there is an auto option, but in practice I did better than auto by balancing the quality and size myself.  Not a complaint, it does say auto is experimental - I probably need to play with it some more though and use the butteraugli.

**Comment by surma** [comment]
A human will always outperform automatic optimization. `auto` is for quick’n’dirty batch use-cases where you want to make sure you do the bare minimum :D

**Comment by spayton** [comment]
Auto seemed to be mostly disregarding any quality matching and just giving the smallest filesize, the quality result was way off anybody's mark.  Probably a problem somewhere, or maybe that the built in auto parameters could be chosen better.  I was npx'ing the cli, it reported being v0.6.1, rather than building the current dev branch, so maybe there's fixes to be had.

I noticed there is no 'verbose/debug' option, it was hard to see if it was doing what I thought it should be doing in auto, especially when it doesn't complain if the parameter is wrong eg.

`--mozjpeg 'auto'` completes quickly without error, but hasn't carried out auto
`--mozjpeg auto` goes away for a very long time, so is probably iterating through all the auto configurations or has simply crashed, no way of knowing unless you wait for an unknown amount of time, a bit of feedback on the auto progress would be useful to both know auto is running and you'd get some sort of indication for how much longer it could take

**Comment by surma** [comment]
Yeah, there was a pretty severe bug with auto optimizer. Fun fact: It only worked reliably with bright images :D

I just published `@squoosh/cli@0.6.2` that fixes that issue and the `Cannot pass non-string to std::string` issue. Can you give it a try?

**Comment by spayton** [comment]
Sure, 0.6.2 is much better, here's the difference.

Source image for all tests

![t2b](https://user-images.githubusercontent.com/4949575/108851954-ecbd0e80-75dc-11eb-81cd-721c213c3037.png)

0.6.1 using --mozjpeg auto

![t2b-0 6 1-auto](https://user-images.githubusercontent.com/4949575/108852135-1bd38000-75dd-11eb-8353-7a17b032c1c5.jpg)

0.6.2 using -- mozjpeg auto

![t2b-0 6 2-auto](https://user-images.githubusercontent.com/4949575/108852168-2a219c00-75dd-11eb-9c3c-74aef75ec18b.jpg)

Great, thats more like it, I'll try it again, rather than thinking it's not worth trying again.

I did notice on 0.6.2 that the command line options -V and -h are broken, or at least fill my terminal with error text such that if it did display anything, my screen buffer wasn't big enough.

I like this CLI version, I had just been rolling my own image conversion wrapper when I came across this.  The feature I needed which I didn't find in any of the other tools I looked at, was to take a single input and generate multiple outputs.  I'll probably abort my own tool and contribute some time to this instead.

**Comment by surma** [comment]
Gonna close this then. 

If you want to provide more context on the `-h` and `-V` issue, because those are working fine for me. (Don’t mind the v0.6.3, I just did another publish because `-V` for 0.6.2 printed 0.6.0 lol 🤦 )

![Screen Shot 2021-02-23 at 14 59 00](https://user-images.githubusercontent.com/234957/108861967-b33dd080-75e7-11eb-828a-155825011e26.png)

**Comment by spayton** [comment]
on win10 x64, with node 12.20.0, this the tail end of

`npx @squoosh/cli@0.6.2 -V`

![image](https://user-images.githubusercontent.com/4949575/108866199-e1251400-75eb-11eb-9ce8-cd12f45fa9ca.png)

**Comment by surma** [comment]
Ah Windows, a constant source of joy 🙄 

This seems like a path issue. I’ll look into it.

**Comment by spayton** [comment]
Ha, I know what you mean.  I also run node under nvm (4 windows), that dynamic duo can be doubly joyful.

Some more info, The previous ver 0.6.1 works fine when run like this

![image](https://user-images.githubusercontent.com/4949575/108889297-22292280-7604-11eb-84cd-3b169f718c80.png)

but then trying this:

`npx @squoosh/cli@0.6.1 -V`

 fails just like above

so it seems more likely its a problem when specifying the version with npx, than a new problem with the current build.

I installed it globally with npm and its fine -

![image](https://user-images.githubusercontent.com/4949575/108890116-12f6a480-7605-11eb-8a81-ef6df470c91e.png)
