### ISSUE TITLE
[CLI] hierarchical output

### ISSUE THREAD

**Issue by illycz** [GoogleChromeLabs/squoosh#967]
**Describe the solution you'd like**
If I'm select images within glob and subfolders, I'm expect, that final output to respect the input hierarchy.

Thanks

**Comment by illycz** [comment]
Ideally, If I'm not specify output, the newly generated images would overwrite the original ones.

**Comment by surma** [comment]
I am hesitant to make the CLI destructive by default. But maintaining folder structure sounds reasonable.

**Comment by dpschen** [comment]
> Ideally, If I'm not specify output, the newly generated images would overwrite the original ones.

This would be nice as an additional option.

**Comment by illycz** [comment]
Anything new about that? Thanks

**Comment by Draghmar** [comment]
I really would like to get hierarchical output because that would make batch compression so much easier. :)

**Comment by surma** [comment]
Yeah, we got this on the roadmap :)

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
